# Generated by Django 2.2.10 on 2020-02-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200213_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creates_date',
            new_name='created_date',
        ),
    ]
